class Commands:
    LEECH = "leech"
    PURGE = "dall"
    PAUSEALL = "pall"
    RESUMEALL = "rall"
    STATUS = "status"
    SETTINGS = "set"
    EXEC = "cmd"
    UPLOAD = "upload"
    YTDL = "ytdl"
    PYTDL = "pytdl"
    ABOUT = "about"
    GETLOGS = "log"
    SERVER = "server"
    USERSETTINGS = "usetting"
    INSTADL = "instadl"